### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PCManiacpt** [OCSInventory-NG/OCSInventory-ocsreports#1008]
**OCS Inventory version**
Version : 2.7

**Describe the bug**
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given

**To Reproduce**
```
PHP Warning:  array_key_exists() expects parameter 2 to
 be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/ipdi
scover/Ipdiscover.php on line 307, referer: http://172.16.110.55/ocsreports/inde
x.php?function=show_ipdiscover

PHP Warning:  array_key_exists() expects parameter 2 to
 be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/sear
ch/Search.php on line 1119, referer: http://172.16.110.55/ocsreports/index.php?f
irst
```

**Expected behavior**
No errors on Apache's error_log

**Additional context**
SO: Slackware Current (to-be 15) x64
Kernel: 5.4.59
Apache: Apache/2.4.46 (Unix) PHP/7.4.9 mod_perl/2.0.11 Perl/v5.32.0
PHP: 7.4.9
mariadb: 10.5.5

**Comment by gillesdubois** [comment]
Hi,

The latest PR should fix this behavior.

Regards,
Gilles Dubois.

**Comment by PCManiacpt** [comment]
Greetings @gillesdubois , 

I just git pulled it and the errors still happen.

`[Mon Aug 24 11:21:25.924528 2020] [php7:warn] [pid 11459:tid 140131332835072] [client 172.16.110.7:55914] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/ipdiscover/Ipdiscover.php on line 307, referer: http://172.16.110.55/ocsreports/index.php?function=show_ipdiscover
`
