### ISSUE TITLE
Anywhere scrollbars - bad overview

### ISSUE THREAD

**Issue by Dennis1993** [OCSInventory-NG/OCSInventory-ocsreports#250]
Hello,
I'm interested in OCS Inventory NG and use your demo to check the functions. Now I have one question:

Why is a scrollbar on the bottom of every table?
I think it is not needed.

![image](https://cloud.githubusercontent.com/assets/1473674/26215874/3e13b00e-3c02-11e7-970c-0244ee27efe9.png)

![image](https://cloud.githubusercontent.com/assets/1473674/26215894/5a68b740-3c02-11e7-8c78-713fbc1df0c3.png)

And why is in the dropdown menu everytime "Office Lizenzen"? A harddisk cannot be filtered by Office licenses.

Maybe we can discuss that to improve it :)

Thanks in advance!

**Comment by MyTheValentinus** [comment]
Hello,
Thanks, this is bug depend on your navgiator and screen size for scrollbar !
We looking for Ofccie un hard disk datatable. Thanks for your report
Have nice day

**Comment by Dennis1993** [comment]
I use Firefox 53.0.3 and Microsoft Edge and the scrollbar ist everytime shown. Monitors are always 1920x1080px (Full HD).

Can I fix it for my current installation or it is a bigger problem, because I have a test installation at the moment and I'm interested in it to use it in our production environment?

Thanks for your quick response!

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed recently and will be available in the next minor version.

Regards,
Gilles Dubois.

**Comment by Dennis1993** [comment]
Hello,
in 2.4 the bug still exists. Is that right?
How can I fix it manually? :)
