### ISSUE TITLE
update to 2.5 broke administrativ data

### ISSUE THREAD

**Issue by Scifire** [OCSInventory-NG/OCSInventory-ocsreports#548]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04.5 LTS

### Server installation method ( Only one choice )
- Install SH

### Server informations
Php version : 7.0.30
Mysql: Ubuntu) version 5.7.23-0ubuntu0.16.04.1
Apache version :  Apache/2.4.18 (Ubuntu)

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
After the update to 2.5 the administrativ data fields with select is broken.
![image](https://user-images.githubusercontent.com/17220258/44151988-6f42c180-a0a4-11e8-9b34-b55a054245a1.png)
I can´t see what was selected before and are unable to select something.

It is also not possible to edit any administrativ data filed it will every time link me to "new tab".

also the date field looks broken since "type" is empty like the select field.
![image](https://user-images.githubusercontent.com/17220258/44152173-1aecd4bc-a0a5-11e8-9fd1-31d7d7d469f7.png)

If i create new one´s it will work.

**Comment by Scifire** [comment]
@charleneauger i tried to se this fix manually but it hadn´t worked. I updated the installation, changed the two lines and started then the apache service and upgraded the DB, still the same problem.

**Comment by Scifire** [comment]
@charleneauger that´s what i did. Didn´t worked administrative data is still broken.

**Comment by charleneauger** [comment]
@Scifire  can you send me a screenshot of your accountinfo_config table from your database please?

Regards,
Charlene

**Comment by Scifire** [comment]
@charleneauger before or after the update? As long as this is not fixed we can´t use it live.
So before update:

```
mysql> describe accountinfo_config;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| ID               | int(11)      | NO   | PRI | NULL    | auto_increment |
| NAME_ACCOUNTINFO | varchar(255) | YES  |     | NULL    |                |
| TYPE             | int(11)      | YES  |     | NULL    |                |
| NAME             | varchar(255) | YES  |     | NULL    |                |
| ID_TAB           | int(11)      | YES  |     | NULL    |                |
| COMMENT          | varchar(255) | YES  |     | NULL    |                |
| SHOW_ORDER       | int(11)      | NO   |     | NULL    |                |
| ACCOUNT_TYPE     | varchar(255) | YES  |     | NULL    |                |
| DEFAULT_VALUE    | varchar(255) | YES  |     | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)

```

**Comment by charleneauger** [comment]
Thamk's and after the update, the table is the same? @Scifire

**Comment by Scifire** [comment]
@charleneauger wait. i´ve overseen that you posted another PR since the first fix. I´ll test this on Monday and give you feedback.

**Comment by charleneauger** [comment]
@Scifire Thank's

**Comment by Scifire** [comment]
@charleneauger i´ve inserted now the code you mentioned.
The administrativ data will now be shown correctly in the ui but i´m missing our data filled in from one of the fields.
It´s the field "Standort" which is a RADIOBUTTON.

**Comment by charleneauger** [comment]
Hi @Scifire ,

This bug has been fixed, Fix: https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/586

Regards,
Charlene Auger

**Comment by Scifire** [comment]
@charleneauger i made the changes from the fix but there´s still no data in the fields.
Or is this needed before the update?

**Comment by Scifire** [comment]
@charleneauger any news on this? Still not able to update until i know how to proceed here

**Comment by charleneauger** [comment]
Hi @Scifire ,

Sorry for the delay.
What is your current version of reports ?

Regards,
Charlene

**Comment by Scifire** [comment]
@charleneauger Our live system has version 2.4.1

**Comment by charleneauger** [comment]
@Scifire , I just tested from a version 2.4.1 to a version 2.5 with radio button but I have not met your problem ... My radio button have updated correctly.
I advise you to recreate this administrative data if it is possible.

Regards,
Charlene

**Comment by Scifire** [comment]
@charleneauger the problem is not the button the problem is the data we already filled in. This data is lost after the update (for example the install date or the location).
And no i´m not willing to fill out the administrative data of our over 400 inventoried hosts.
