### ISSUE TITLE
[BUG]Service-Pack wrong info on Linux Clients

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/OCSInventory-ocsreports#741]
**OCS Inventory version**
Version :  2.6
Linux Client: 2.4.2

**Describe the bug**
SLES 12 SP4 shown as follow:

OS Name :SUSE Linux Enterprise Server 12 (x86_64)
OS Version :4.12.14-95.13-default
Service pack :#1 SMP Fri Mar 22 06:04:58 UTC 2019 (c01bf34)

The Infos are wrong, 
OS Name : SUSE Linux Enterprise Server 12 (x86_64) --> correct
OS Version : 4.12.14-95.13-default --> wrong (This is the Kernel Version, OS Version is 12)
Service pack :#1 SMP Fri Mar 22 06:04:58 UTC 2019 (c01bf34) --> wrong (this is the Date from the Kernel, not the Service Pack, the Service pack is 4)

**Expected behavior**
OS Name : SUSE Linux Enterprise Server 12 (x86_64) 
OS Version : 12
Service pack : 4
Kernel Version: 4.12.14-95.13-default

**Screenshots**
![image](https://user-images.githubusercontent.com/8693550/57927512-84d98000-78ae-11e9-8e79-b3851f7c025f.png)

**Comment by fbomj** [comment]
Please post content of /etc/SuSE-release file

**Comment by LMS235** [comment]
/etc/SuSE-release

```
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 4
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
```

/etc/os-release

```
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles_sap:12:sp4"
```

**lsb_release is per default NOT installed on a SLES server!**
lsb_release -a

```
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP4
Release:        12.4
Codename:       n/a
```

**Comment by fbomj** [comment]
Fix with this PR => https://github.com/OCSInventory-NG/UnixAgent/pull/201

**Comment by LMS235** [comment]
I see you read "/etc/SuSE-release" but in the future the file will be deleted.
You should use "/etc/os-release" instead.

**Comment by fbomj** [comment]
This will be corrected in next release.

**Comment by LMS235** [comment]
Ok, thanks :)

**Comment by LMS235** [comment]
New Version of the Agent and the following in the log

```
[Mon May 20 15:04:28 2019][debug] Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Slackware ignored
[Mon May 20 15:04:28 2019][debug]  - /etc/SuSE-release can be read
[Mon May 20 15:04:28 2019][debug] Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::Trustix ignored
```

but the output is still wrong (now BS Name only "SUSE"):

![image](https://user-images.githubusercontent.com/8693550/58028618-675d1e00-7b1b-11e9-8ca1-8a5841dc0750.png)

**Comment by fbomj** [comment]
The file SuSE.pm has not been be updated correctly. Please verify.

**Comment by LMS235** [comment]
this is the "/usr/lib/perl5/site_perl/5.18.2/Ocsinventory/Agent/Backend/OS/Linux/Distro/NonLSB/SuSE.pm" from the affected client

```
package Ocsinventory::Agent::Backend::OS::Linux::Distro::NonLSB::SuSE;
use strict;

sub check {
    my $params = shift;
    my $common = $params->{common};
    $common->can_read ("/etc/SuSE-release")
}

sub run {
    my $v;
    my $version;
    my $patchlevel;

    my $params = shift;
    my $common = $params->{common};

    open V, "</etc/SuSE-release" or warn;
    foreach (<V>) {
        next if (/^#/);
        $version=$1 if (/^VERSION = ([0-9]+)/);
        $patchlevel=$1 if (/^PATCHLEVEL = ([0-9]+)/);
    }
    close V;

    $common->setHardware({
        OSNAME => "SUSE Linux Enterprise Server $version SP$patchlevel",
        OSVERSION => $version,
        OSCOMMENTS => $patchlevel
    });
}

1;
```

compare is identical with https://raw.githubusercontent.com/OCSInventory-NG/UnixAgent/master/lib/Ocsinventory/Agent/Backend/OS/Linux/Distro/NonLSB/SuSE.pm

**Comment by LMS235** [comment]
i found the error.... for your question i installed "lsb-release" so the agent use this info...
after remove "lsb-release" the info is correct....

but this is also wrong :(

**Comment by fbomj** [comment]
what's wrong?

**Comment by LMS235** [comment]
when a sles server has installed "lsb-release" then the information is wrong again.

SLES without "lsb-release":
![image](https://user-images.githubusercontent.com/8693550/58029791-9d030680-7b1d-11e9-8c8b-b5943ee8790f.png)

SLES with installed "lsb-release":
![image](https://user-images.githubusercontent.com/8693550/58029816-a8eec880-7b1d-11e9-9ed8-0dea842cfdf6.png)

**Comment by fbomj** [comment]
OK. I'll check lsb_release informations.

**Comment by LMS235** [comment]
Normally "lsb_release" is NOT installed on SLES (probably that's why it hasn't been noticed yet).

**Comment by LMS235** [comment]
For example /etc/os-release can be used with SLES, SLE, OpenSuSE and also with Ubuntu (I know it there anyway).

**Comment by fbomj** [comment]
We want to keep compatibility with older linux. The reading of /etc/os-release file is coming.

**Comment by LMS235** [comment]
ok, i understand. but until now, the lsb_release infos overwrite the infos from your update.

so if the infos from /etc/SuSE-release can be read, the lsb_release infos should be ignored (or only the kernel info should be used, actually not shown within the SuSE Infos).

**Comment by fbomj** [comment]
By default first lsb_release infos are sent if lsb_release command is present otherwise /etc/<distro>-release file is read when lsb_release command is missing.

**Comment by LMS235** [comment]
Is it not possible for example

if /etc/os-release exist --> use it
elif /etc/SuSE-release exist --> use it
else use lsb_release?
